version: 1
formatters:
  verbose:
    format: '%(asctime)s [%(levelname)s]: %(message)s - %(filename)s:%(module)s:%(funcName)s:%(lineno)d'
    datefmt: '%Y-%m-%d %H:%M:%S'
  simple:
    format: '%(asctime)s [%(levelname)s]: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  fileHandler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: verbose
    filename: 'log/application.log'
    maxBytes: 100000
    backupCount: 1
loggers:
  notion_toys:
    level: INFO
    handlers: [consoleHandler, fileHandler]
    propagate: no
root:
  level: INFO
  handlers: []
